daou:
  rate-limit:
    capacity: 10
    time: 10
    unit: seconds
  root-path: /Users/son-youngjun/IdeaProjects/test/Daou/src/main/resources/file
  access-ip-address:
    - 192.168.51.17
    - 192.168.51.0/24
    - 127.0.0.1

spring:
  application:
    name: daou

springdoc:
  #  version: '@springdoc.version@'
  api-docs:
    groups:
      enabled: true
    resolve-schema-properties: true
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: false